import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Semana 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/book.png" />
      </Head>
      <h1>Fórmula E-motion</h1>
      <p>Estudar o Cicruito pré-carga</p>
      
      
      
      
      
      </div>
  )
}
