import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Agenda Geral</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/book.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Agenda Geral
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/circuitos/p1" className={styles.card}>
            <h2>Circuitos 1</h2>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Circuitos Lógicos</h2>
            
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Automação Industrial</h2>
            <p>
            Matérias e Anotações.
            </p>
            
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Anotações Gerais</h2>
            <p>
            NOVEMBRO/2021.
            </p>
          </a>
        </div>
      </main>

      
    </div>
  )
}
